services:
  db:
    image: mongo
    container_name: aavartan_db
    ports:
      - "27018:27017"
    restart: always
    volumes:
      - ./db:/data/db

  
  mongo-gui:
    image: mongo-express:latest
    container_name: mongo-gui
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://db:27017/gues-2024?ssl=false'
      ME_CONFIG_SITE_BASEURL: '/dbadmin'
      ME_CONFIG_OPTIONS_EDITORTHEME: 'ambiance'
      ME_CONFIG_OPTIONS_READONLY: false
      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'pass'
    depends_on:
      - db
    
  api:
    build: .
    container_name: api
    ports:
      - "5000:5000"
    env_file:
      - .env
